"""Layer-wise answer cognition and confidence metacognition experiments."""

from .prompts import (
    ASSISTANT_ANSWER_PREFILL,
    ASSISTANT_CONFIDENCE_PREFILL,
    STAGE1_MULTIMODAL_ANSWER_PROMPT,
    STAGE2_CONFIDENCE_PROMPT,
)

__all__ = [
    "ASSISTANT_ANSWER_PREFILL",
    "ASSISTANT_CONFIDENCE_PREFILL",
    "STAGE1_MULTIMODAL_ANSWER_PROMPT",
    "STAGE2_CONFIDENCE_PROMPT",
]
