from __future__ import annotations

from pathlib import Path

from dp_SA.real_sa.config import (
    BOOTSTRAP_REPEATS, MAX_PIXELS, MIN_PIXELS, MODEL_PATH, SEED, TEMPERATURE,
    TRAIN_MANIFEST,
)

PACKAGE_ROOT = Path(__file__).resolve().parent
OUTPUT_ROOT = PACKAGE_ROOT / "output"
MEAN_REAL_SA_ROOT = PACKAGE_ROOT.parent / "output"
MEAN_CONDITION_SCORES = MEAN_REAL_SA_ROOT / "artifacts" / "condition_scores.jsonl"
MEAN_CASE_METRICS = MEAN_REAL_SA_ROOT / "tables" / "real_sa_per_case.csv"
MEAN_PROCESSOR_AUDIT = MEAN_REAL_SA_ROOT / "progress" / "processor_audit.json"

REPLICATES = 5
NOISE_MEAN = 127.5
NOISE_STD = 63.75
MIN_TOKEN_FREQUENCY = 5
CONDITIONS = ("clean", "10_random_text", "01_gaussian_image", "00_both_random")
CORRUPT_CONDITIONS = CONDITIONS[1:]
CLEAN_PROBABILITY_TOLERANCE = 1e-12
EQUIVALENCE_TOLERANCE = 1e-12

__all__ = [
    "BOOTSTRAP_REPEATS", "CLEAN_PROBABILITY_TOLERANCE", "CONDITIONS",
    "CORRUPT_CONDITIONS", "EQUIVALENCE_TOLERANCE", "MAX_PIXELS",
    "MEAN_CASE_METRICS", "MEAN_CONDITION_SCORES", "MEAN_PROCESSOR_AUDIT",
    "MIN_PIXELS", "MIN_TOKEN_FREQUENCY", "MODEL_PATH", "NOISE_MEAN", "NOISE_STD",
    "OUTPUT_ROOT", "PACKAGE_ROOT", "REPLICATES", "SEED", "TEMPERATURE",
    "TRAIN_MANIFEST",
]
